version: "3"

services:
  chrome:
    image: selenium/standalone-chrome:4.1.3
    hostname: chrome
    privileged: true
    shm_size: '3gb'

  test-run:
    build: .
    container_name: test-run
    depends_on:
      - chrome
    links:
      - chrome
    environment:
      - MODULE=testng.xml
    volumes:
      - ./src/test/resources/results:/app